/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrototypeCmsRouteImport } from './routes/prototype-cms'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellAddOnsRouteImport } from './routes/_shell.add-ons'
import { Route as ShellAppointmentsRouteImport } from './routes/_shell.appointments'
import { Route as ShellBranchesRouteImport } from './routes/_shell.branches'
import { Route as ShellPackagesRouteImport } from './routes/_shell.packages'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellStudioServicesRouteImport } from './routes/_shell.studio-services'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeCmsRoute = PrototypeCmsRouteImport.update({
  id: '/prototype-cms',
  path: '/prototype-cms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAddOnsRoute = ShellAddOnsRouteImport.update({
  id: '/add-ons',
  path: '/add-ons',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAppointmentsRoute = ShellAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBranchesRoute = ShellBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPackagesRoute = ShellPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellStudioServicesRoute = ShellStudioServicesRouteImport.update({
  id: '/studio-services',
  path: '/studio-services',
  getParentRoute: () => ShellRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/prototype-cms': typeof PrototypeCmsRoute
  '/add-ons': typeof ShellAddOnsRoute
  '/appointments': typeof ShellAppointmentsRoute
  '/branches': typeof ShellBranchesRoute
  '/packages': typeof ShellPackagesRoute
  '/settings': typeof ShellSettingsRoute
  '/studio-services': typeof ShellStudioServicesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/prototype-cms': typeof PrototypeCmsRoute
  '/add-ons': typeof ShellAddOnsRoute
  '/appointments': typeof ShellAppointmentsRoute
  '/branches': typeof ShellBranchesRoute
  '/packages': typeof ShellPackagesRoute
  '/settings': typeof ShellSettingsRoute
  '/studio-services': typeof ShellStudioServicesRoute
  '/': typeof ShellIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/prototype-cms': typeof PrototypeCmsRoute
  '/_shell/add-ons': typeof ShellAddOnsRoute
  '/_shell/appointments': typeof ShellAppointmentsRoute
  '/_shell/branches': typeof ShellBranchesRoute
  '/_shell/packages': typeof ShellPackagesRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/studio-services': typeof ShellStudioServicesRoute
  '/_shell/': typeof ShellIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/prototype-cms'
    | '/add-ons'
    | '/appointments'
    | '/branches'
    | '/packages'
    | '/settings'
    | '/studio-services'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/prototype-cms'
    | '/add-ons'
    | '/appointments'
    | '/branches'
    | '/packages'
    | '/settings'
    | '/studio-services'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/prototype-cms'
    | '/_shell/add-ons'
    | '/_shell/appointments'
    | '/_shell/branches'
    | '/_shell/packages'
    | '/_shell/settings'
    | '/_shell/studio-services'
    | '/_shell/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrototypeCmsRoute: typeof PrototypeCmsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype-cms': {
      id: '/prototype-cms'
      path: '/prototype-cms'
      fullPath: '/prototype-cms'
      preLoaderRoute: typeof PrototypeCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/add-ons': {
      id: '/_shell/add-ons'
      path: '/add-ons'
      fullPath: '/add-ons'
      preLoaderRoute: typeof ShellAddOnsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/appointments': {
      id: '/_shell/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof ShellAppointmentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/branches': {
      id: '/_shell/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof ShellBranchesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/packages': {
      id: '/_shell/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof ShellPackagesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/studio-services': {
      id: '/_shell/studio-services'
      path: '/studio-services'
      fullPath: '/studio-services'
      preLoaderRoute: typeof ShellStudioServicesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellAddOnsRoute: typeof ShellAddOnsRoute
  ShellAppointmentsRoute: typeof ShellAppointmentsRoute
  ShellBranchesRoute: typeof ShellBranchesRoute
  ShellPackagesRoute: typeof ShellPackagesRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellStudioServicesRoute: typeof ShellStudioServicesRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAddOnsRoute: ShellAddOnsRoute,
  ShellAppointmentsRoute: ShellAppointmentsRoute,
  ShellBranchesRoute: ShellBranchesRoute,
  ShellPackagesRoute: ShellPackagesRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellStudioServicesRoute: ShellStudioServicesRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  PrototypeCmsRoute: PrototypeCmsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
